name: dart_nostr
description: This is a helper package that simplify and accelerate the use of Nostr protocal in Dart/Flutter environment
version: 1.0.5
repository: https://github.com/anasfik/nostr/

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bip340: ^0.1.0
  equatable: ^2.0.5
  convert: ^3.1.1
  crypto: ^3.0.2
  http: ^0.13.5

dev_dependencies:
  lints:
  test:
