name: nostr
description: This is a helper package that simplify and accelerate the use of Nostr protocal in Dart/Flutter environment
version: 1.0.0-dev
repository: https://github.com/anasfik/nostr/

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bip340:
  equatable:

dev_dependencies:
  lints:
  test:
